server:
  port: ${API_GATEWAY_PORT:8000}

spring:
  config:
    import: optional:file:.env[.properties]
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: shard_service
          uri: ${SHARD_SERVICE_URL} #http://localhost:3015
          predicates:
            - Path=/shard_service/**
          filters:
            - StripPrefix=1

        - id: user_service
          uri: ${USER_SERVICE_URL} #http://localhost:8002
          predicates:
            - Path=/user_service/**
          filters:
            - StripPrefix=1

        - id: messenger_service
          uri: ${MESSENGER_SERVICE_URL} #http://localhost:8001
          predicates:
            - Path=/messenger_service/**
          filters:
            - StripPrefix=1

        - id: notification_service
          uri: ${NOTIFICATION_SERVICE_URL} #http://localhost:8002
          predicates:
            - Path=/notification_service/**
          filters:
            - StripPrefix=1
